[package]
name = "xtask"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
publish = false

[dependencies]
dust-config.workspace = true
dust-data.workspace = true
flate2.workspace = true
serde.workspace = true
serde_json.workspace = true

[lints]
workspace = true
