//! The outside check: Minecraft 1.21.1's own data, all 5,549 files of it.
//!
//! # Why this test is the one that matters
//!
//! Every other test in this crate is written by the same person who wrote the
//! loader, against the loader's own idea of what a datapack is. A synthetic
//! pack that round-trips through this code proves the two halves agree with
//! each other, which is not the question — Phase 0.5 proved that the hard way,
//! when swapping the two slowest properties of every block left all 26,684
//! block states round-tripping perfectly and put every chest at the wrong id.
//!
//! So something from outside sits beside it, and here it is Mojang's data.
//! Nobody here wrote it, nobody here can adjust it to agree, and it exercises
//! shapes an invented fixture would not have thought of: 430 entries in one
//! tag, a four-deep reference chain, two complete datapacks nested inside the
//! vanilla tree, and a `pack.mcmeta` whose description is a translation key
//! rather than a string.
//!
//! The numbers asserted below were computed by a **separate implementation** —
//! a short Python script that walks the same tree — rather than by reading them
//! off this loader's output and writing them down. A number taken from the
//! thing under test is not a check on it.
//!
//! # Why it skips instead of failing
//!
//! The corpus is generated by `cargo xtask extract`, needs a network and a JDK,
//! and is gitignored because no Mojang file is committed. CI has none of that.
//! A test that silently passes when its fixture is missing is worse than no
//! test, so the skip is written to the real stderr handle, which the test
//! harness does not capture — it appears on a green run.

mod support;

use std::collections::BTreeSet;
use std::time::Instant;

use dust_data::registry::RegistryId;
use dust_data::vocabulary::Unchecked;
use dust_data::{load, DirectoryPack, LoadOptions, PackSource, ResourceLocation, DUST_PACK_FORMAT};

/// Files under `data/minecraft/` that are not inside the two nested datapacks.
///
/// Counted independently: `find data -name '*.json' | grep -v /datapacks/`.
const EXPECTED_FILES: usize = 5_549;
/// Tag files among them.
const EXPECTED_TAGS: usize = 530;
/// The rest.
const EXPECTED_RESOURCES: usize = EXPECTED_FILES - EXPECTED_TAGS;
/// Entries written across every tag file, before any `#` is followed.
const EXPECTED_ENTRIES_BEFORE: usize = 3_852;
/// Members across every tag after flattening. Larger than the written count
/// because a reference expands, smaller than a naive sum because a set
/// deduplicates.
const EXPECTED_ENTRIES_AFTER: usize = 6_411;
/// `#minecraft:completes_find_tree_tutorial` → `#logs` → `#logs_that_burn` →
/// `#oak_logs`.
const EXPECTED_DEEPEST_CHAIN: usize = 4;
/// `#minecraft:mineable/pickaxe`.
const EXPECTED_WIDEST: usize = 430;
/// Written entries that name a member rather than another tag: 3,852 entries
/// less the 284 that begin with `#`. This is what an unvalidated count counts —
/// lines in files, not members of resolved sets — and it is deliberately not
/// the same number as [`EXPECTED_ENTRIES_AFTER`].
const EXPECTED_MEMBER_ENTRIES: usize = 3_568;
/// `#minecraft:logs`, whose three written entries are all references. This is
/// the number a non-transitive resolver gets wrong, and it gets it wrong by
/// returning 0 rather than 3, because all three entries are references and a
/// resolver that does not follow them has nothing left.
const EXPECTED_LOGS: usize = 40;

fn location(text: &str) -> ResourceLocation {
    ResourceLocation::parse(text).expect("a valid name")
}

#[test]
fn the_whole_vanilla_data_tree_loads_with_no_errors() {
    let Some(root) = support::corpus_root() else {
        support::skipped(
            "the_whole_vanilla_data_tree_loads_with_no_errors",
            "the extracted 1.21.1 data tree is not on this machine",
        );
        return;
    };

    // The vanilla tree has no pack.mcmeta of its own: Minecraft's built-in pack
    // describes itself from inside the jar. `builtin` is the constructor that
    // says so, rather than making a missing pack.mcmeta acceptable everywhere.
    let pack = DirectoryPack::builtin(&root, "vanilla", DUST_PACK_FORMAT);
    let started = Instant::now();
    let data = load(&[&pack as &dyn PackSource], &LoadOptions::default());
    let load_time = started.elapsed();

    let resolve_started = Instant::now();
    let (tags, tag_findings) = data.resolve_tags(&Unchecked);
    let resolve_time = resolve_started.elapsed();

    support::report(&[
        format!("vanilla corpus at {}", root.display()),
        format!(
            "load    {:?} for {} files ({} read, {} skipped)",
            load_time,
            data.stats().files_seen,
            data.stats().files_read,
            data.packs()[0].files_skipped,
        ),
        format!(
            "resolve {resolve_time:?} for {} tags, {} entries in, {} out",
            tags.stats().tags,
            tags.stats().entries_before,
            tags.stats().entries_after,
        ),
        format!(
            "        deepest chain {} at {:?}, widest {} at {:?}",
            tags.stats().deepest_chain,
            tags.stats().deepest_tag,
            tags.stats().widest_size,
            tags.stats().widest_tag,
        ),
        format!(
            "        {} findings, {} of them errors",
            data.findings().len() + tag_findings.len(),
            data.error_count() + dust_data::error_count(&tag_findings),
        ),
    ]);

    // Every error here is a finding about this loader, not about Mojang.
    let errors: Vec<String> = data
        .findings()
        .iter()
        .chain(tag_findings.iter())
        .filter(|f| f.severity == dust_data::Severity::Error)
        .map(ToString::to_string)
        .collect();
    assert!(
        errors.is_empty(),
        "{} error(s) loading vanilla:\n{}",
        errors.len(),
        errors.join("\n")
    );

    assert_eq!(data.stats().files_read, EXPECTED_FILES);
    assert_eq!(data.stats().resources, EXPECTED_RESOURCES);
    assert_eq!(data.stats().tags, EXPECTED_TAGS);
    assert_eq!(data.stats().overrides, 0, "one pack cannot override itself");
    assert_eq!(
        data.namespaces(),
        BTreeSet::from(["minecraft"]),
        "vanilla ships one namespace"
    );
    assert!(tags.cycles().is_empty(), "{:?}", tags.cycles());
}

#[test]
fn the_vanilla_tags_resolve_to_the_numbers_a_separate_walk_produces() {
    let Some(root) = support::corpus_root() else {
        support::skipped(
            "the_vanilla_tags_resolve_to_the_numbers_a_separate_walk_produces",
            "the extracted 1.21.1 data tree is not on this machine",
        );
        return;
    };
    let pack = DirectoryPack::builtin(&root, "vanilla", DUST_PACK_FORMAT);
    let data = load(&[&pack as &dyn PackSource], &LoadOptions::default());
    let (tags, findings) = data.resolve_tags(&Unchecked);
    assert!(findings.is_empty(), "{findings:?}");

    let stats = tags.stats();
    assert_eq!(stats.tags, EXPECTED_TAGS);
    assert_eq!(stats.entries_before, EXPECTED_ENTRIES_BEFORE);
    assert_eq!(stats.entries_after, EXPECTED_ENTRIES_AFTER);
    assert_eq!(stats.deepest_chain, EXPECTED_DEEPEST_CHAIN);
    assert_eq!(stats.widest_size, EXPECTED_WIDEST);
    assert_eq!(
        stats.widest_tag,
        Some((
            RegistryId::new("tags/block"),
            location("minecraft:mineable/pickaxe")
        ))
    );

    // Vanilla writes no `replace` and no `required: false` anywhere in 1.21.1 —
    // checked against the corpus with grep — so both of those paths are
    // exercised only by the synthetic packs, and nothing here should have been
    // dropped.
    assert_eq!(stats.optional_dropped, 0);

    // With no vocabulary, *nothing* was validated, and the count has to say so
    // rather than a clean run reading as a clean bill of health.
    assert_eq!(stats.validated_entries, 0);
    assert_eq!(stats.unvalidated_entries, EXPECTED_MEMBER_ENTRIES);
}

/// The single assertion a non-transitive resolver fails.
///
/// `#minecraft:logs` is written as three references and nothing else. A
/// resolver that inlines one level deep instead of all the way down produces a
/// set of size 0, not 40 — every entry it holds is a `#`, and dropping them
/// leaves nothing. That is the mutation this test exists to catch, and it is
/// the reason a synthetic three-block tag would not have caught it.
#[test]
fn logs_resolves_all_the_way_down_to_forty_blocks() {
    let Some(root) = support::corpus_root() else {
        support::skipped(
            "logs_resolves_all_the_way_down_to_forty_blocks",
            "the extracted 1.21.1 data tree is not on this machine",
        );
        return;
    };
    let pack = DirectoryPack::builtin(&root, "vanilla", DUST_PACK_FORMAT);
    let data = load(&[&pack as &dyn PackSource], &LoadOptions::default());
    let (tags, _) = data.resolve_tags(&Unchecked);

    let blocks = RegistryId::new("tags/block");
    let logs = tags
        .get(&blocks, &location("minecraft:logs"))
        .expect("vanilla defines #minecraft:logs");
    assert_eq!(logs.len(), EXPECTED_LOGS);
    assert!(logs.contains(&location("minecraft:oak_log")));
    assert!(logs.contains(&location("minecraft:warped_stem")));

    // And the merged form still shows the three references as written, so the
    // flattening is a view rather than a rewrite of the pack.
    let merged = data
        .merged_tag(&blocks, &location("minecraft:logs"))
        .expect("merged");
    assert_eq!(merged.entries.len(), 3);
    assert!(merged
        .entries
        .iter()
        .all(|entry| entry.kind == dust_data::tag::EntryKind::Reference));
}

/// The nested packs inside the vanilla tree are not swallowed into a registry.
///
/// `data/minecraft/datapacks/bundle/` and `.../trade_rebalance/` are two
/// complete datapacks, each with its own `pack.mcmeta`, sixty-six files
/// between them. A loader that walks directories generically turns them into
/// resources named `minecraft:bundle/data/minecraft/recipe/…`, which nothing
/// will ever look up. This asserts they were noticed and left alone.
#[test]
fn the_datapacks_nested_inside_vanilla_are_reported_and_not_absorbed() {
    let Some(root) = support::corpus_root() else {
        support::skipped(
            "the_datapacks_nested_inside_vanilla_are_reported_and_not_absorbed",
            "the extracted 1.21.1 data tree is not on this machine",
        );
        return;
    };
    let pack = DirectoryPack::builtin(&root, "vanilla", DUST_PACK_FORMAT);
    let data = load(&[&pack as &dyn PackSource], &LoadOptions::default());

    let about_datapacks: Vec<&dust_data::Finding> = data
        .findings()
        .iter()
        .filter(|f| f.file.contains("datapacks"))
        .collect();
    assert_eq!(about_datapacks.len(), 1, "{about_datapacks:?}");
    assert_eq!(about_datapacks[0].severity, dust_data::Severity::Warning);
    assert!(
        about_datapacks[0].message.contains("66 file(s)"),
        "{}",
        about_datapacks[0]
    );

    // Nothing from inside them reached a registry.
    for registry in data.registries() {
        for name in data.registry(registry).expect("present").keys() {
            assert!(
                !name.path().contains("datapacks/"),
                "{registry}/{name} came from a nested pack"
            );
        }
    }
}

/// The two packs Mojang nests inside the vanilla tree are ordinary packs, and
/// they are the only `pack.mcmeta` files in the corpus. They are what proves
/// the metadata reader against a file nobody here wrote — in particular a
/// `description` that is a translation component rather than a string.
#[test]
fn mojangs_own_pack_mcmeta_parses_including_its_translated_description() {
    let Some(root) = support::corpus_root() else {
        support::skipped(
            "mojangs_own_pack_mcmeta_parses_including_its_translated_description",
            "the extracted 1.21.1 data tree is not on this machine",
        );
        return;
    };

    for (name, key) in [
        ("bundle", "dataPack.bundle.description"),
        ("trade_rebalance", "dataPack.trade_rebalance.description"),
    ] {
        let path = root.join("data/minecraft/datapacks").join(name);
        let pack = DirectoryPack::open(&path);
        let data = load(&[&pack as &dyn PackSource], &LoadOptions::default());
        assert_eq!(data.error_count(), 0, "{:?}", data.findings());

        let meta = data.packs()[0].meta.as_ref().expect("parsed");
        assert_eq!(meta.pack_format, 48);
        assert_eq!(
            meta.description.as_ref().expect("present").plain_text(),
            format!("{{{key}}}"),
            "a description that is a text component must not come back empty"
        );
        assert_eq!(meta.features, vec![format!("minecraft:{name}")]);
    }
}
