//! Emitting the generated tables as Rust.
//!
//! What lands in the repository is this generated Rust, not Mojang's JSON. The
//! project's Code Provenance document draws that line: the extractor and the
//! generated code are the repository's; Mojang's files stay on the machine that
//! downloaded them.

use std::collections::{BTreeMap, BTreeSet};
use std::fmt::Write as _;

use super::blocks::{Blocks, ReportedBlock};
use super::registries::{Registries, Registry};

/// Every block with properties contributes at least these offsets from its base
/// id to the golden sample.
///
/// Offset 1 is the sharp one: it must differ from the base state in exactly the
/// *last* property, so it fails immediately if the wrong property was decided
/// to vary fastest. The other two spread the check across the range so an error
/// in a middle digit is caught as well.
fn sample_offsets(state_count: u32) -> Vec<u32> {
    let mut offsets = vec![0, 1, state_count / 2, state_count - 1];
    offsets.retain(|o| *o < state_count);
    offsets.sort_unstable();
    offsets.dedup();
    offsets
}

/// Render the generated block module.
pub fn blocks(data: &Blocks, version: &str, reported: &BTreeMap<String, ReportedBlock>) -> String {
    let mut out = String::with_capacity(512 * 1024);

    let _ = writeln!(
        out,
        "// Generated by `cargo xtask extract --version {version}`. Do not edit.\n\
         //\n\
         // Derived from the block report produced by Minecraft {version}'s own data\n\
         // generators, run against a server jar on the machine that generated this. No\n\
         // Mojang file is committed; this is the Rust that resulted from reading one.\n\
         //\n\
         // The property order in each entry is the *state id* order — the first property\n\
         // varies slowest — which is derived from the ids rather than taken from the\n\
         // report's key order, because for four blocks on 1.21.1 those disagree.\n"
    );
    let _ = writeln!(out, "use crate::{{BlockDef, PropertyDef}};\n");
    let _ = writeln!(
        out,
        "/// The Minecraft version this table was generated from."
    );
    let _ = writeln!(out, "pub const DATA_VERSION: &str = {version:?};\n");
    let _ = writeln!(
        out,
        "/// The number of distinct block states, so `0..STATE_COUNT` is every"
    );
    let _ = writeln!(out, "/// id that decodes to something.");
    let _ = writeln!(out, "pub const STATE_COUNT: u32 = {};\n", data.state_count);

    // Value lists repeat heavily — every `facing` with the same six values, every
    // boolean — so they are interned. It roughly halves the file, and a file
    // that appears in every diff of this table is worth keeping small.
    let mut interned: BTreeMap<Vec<String>, String> = BTreeMap::new();
    let mut value_lists = String::new();
    for block in &data.blocks {
        for property in &block.properties {
            if interned.contains_key(&property.values) {
                continue;
            }
            let name = format!("V{}", interned.len());
            let rendered: Vec<String> = property.values.iter().map(|v| format!("{v:?}")).collect();
            let _ = writeln!(
                value_lists,
                "static {name}: &[&str] = &[{}];",
                rendered.join(", ")
            );
            interned.insert(property.values.clone(), name);
        }
    }
    let _ = writeln!(out, "{value_lists}");

    let _ = writeln!(out, "/// Every block, ordered by base state id.");
    let _ = writeln!(out, "pub static BLOCKS: &[BlockDef] = &[");
    for block in &data.blocks {
        let properties: Vec<String> = block
            .properties
            .iter()
            .map(|p| {
                format!(
                    "PropertyDef {{ name: {:?}, values: {} }}",
                    p.name, interned[&p.values]
                )
            })
            .collect();
        let _ = writeln!(
            out,
            "    BlockDef {{ name: {:?}, base_state_id: {}, state_count: {}, \
             default_state_id: {}, properties: &[{}] }},",
            block.name,
            block.base_state_id,
            block.state_count,
            block.default_state_id,
            properties.join(", ")
        );
    }
    let _ = writeln!(out, "];\n");

    // Names are wanted in alphabetical order for lookup and in state-id order
    // for decoding, and one table cannot be both. This is the index that makes
    // a name lookup a binary search instead of a scan of 1,060 strings.
    let mut by_name: Vec<(usize, &str)> = data
        .blocks
        .iter()
        .enumerate()
        .map(|(i, b)| (i, b.name.as_str()))
        .collect();
    by_name.sort_by_key(|(_, name)| *name);
    let _ = writeln!(
        out,
        "/// Indices into [`BLOCKS`], ordered by name, for binary search."
    );
    let _ = writeln!(out, "pub static BLOCKS_BY_NAME: &[u16] = &[");
    for chunk in by_name.chunks(16) {
        let row: Vec<String> = chunk.iter().map(|(i, _)| i.to_string()).collect();
        let _ = writeln!(out, "    {},", row.join(", "));
    }
    let _ = writeln!(out, "];\n");

    samples(&mut out, data, reported);
    out
}

/// A golden sample of the id-to-properties mapping, **taken from the report**
/// rather than from the table above.
///
/// This exists because the round-trip test in `dust-registry` cannot catch the
/// defect this extractor is most likely to have. Decoding a state through the
/// table and re-encoding it through the same table agrees with itself under
/// *any* internally consistent property order, including a wrong one — so a
/// round-trip proves the encoder and the decoder agree with each other, which
/// is not the question. The question is whether they agree with Minecraft, and
/// only something derived independently of the derived order can answer it.
///
/// Each row is `(id, block, "key=value,...")` with the keys sorted
/// **alphabetically**, which deliberately encodes nothing about the radix
/// order. If the property order is wrong, the values decoded for a given id
/// change, and these rows stop matching.
///
/// Every block that has properties contributes rows, so coverage is per block
/// rather than a stride across the id space — a stride misses whole blocks, and
/// a block is the unit the order is decided for.
fn samples(out: &mut String, data: &Blocks, reported: &BTreeMap<String, ReportedBlock>) {
    let _ = writeln!(
        out,
        "/// A sample of the id-to-properties mapping as Mojang\'s report states it,\n\
         /// with property names sorted alphabetically so that nothing here encodes\n\
         /// the order the ids actually use. Every block with properties is\n\
         /// represented. See `crates/dust-registry/tests/` for why a self-consistent\n\
         /// round-trip is not enough on its own."
    );
    let _ = writeln!(out, "pub static STATE_SAMPLES: &[(u32, &str, &str)] = &[");

    let mut rows = Vec::new();
    for block in &data.blocks {
        let Some(report) = reported.get(&block.name) else {
            continue;
        };
        if block.properties.is_empty() {
            continue;
        }
        let wanted: Vec<u32> = sample_offsets(block.state_count)
            .iter()
            .map(|o| block.base_state_id + o)
            .collect();
        for state in &report.states {
            if !wanted.contains(&state.id) {
                continue;
            }
            // BTreeMap iterates in key order, which is the alphabetical
            // ordering this row depends on being independent of the radix.
            let pairs: Vec<String> = state
                .properties
                .iter()
                .map(|(k, v)| format!("{k}={v}"))
                .collect();
            rows.push((state.id, block.name.clone(), pairs.join(",")));
        }
    }
    rows.sort_by_key(|(id, _, _)| *id);
    for (id, name, properties) in &rows {
        let _ = writeln!(out, "    ({id}, {name:?}, {properties:?}),");
    }
    let _ = writeln!(out, "];");
}

/// A registry contributes these positions in its protocol-id sequence to the
/// golden sample.
///
/// Both ends and three points across the middle. The ends are what an
/// off-by-one moves first; the middle points are what a wrong sort moves, since
/// a table sorted by the wrong key can still have the same first and last
/// entries by luck. Small registries collapse to fewer rows once these are
/// deduplicated, and a registry of one contributes one row.
fn registry_sample_ids(entry_count: u32) -> Vec<u32> {
    let mut ids = vec![
        0,
        1,
        entry_count / 4,
        entry_count / 2,
        entry_count / 4 * 3,
        entry_count - 1,
    ];
    ids.retain(|id| *id < entry_count);
    ids.sort_unstable();
    ids.dedup();
    ids
}

/// The Rust identifier a registry's statics are named after.
///
/// `minecraft:worldgen/biome_source` becomes `WORLDGEN_BIOME_SOURCE`. The
/// `minecraft` namespace is dropped because every registry on 1.21.1 is in it
/// and carrying it would make every name eleven characters longer for no
/// distinction; any other namespace is kept, because then it *is* the
/// distinction. Collisions are checked by the caller rather than assumed away.
fn registry_ident(name: &str) -> String {
    let stem = name.strip_prefix("minecraft:").unwrap_or(name);
    let mut ident: String = stem
        .chars()
        .map(|c| if c.is_ascii_alphanumeric() { c } else { '_' })
        .collect();
    ident.make_ascii_uppercase();
    if ident.starts_with(|c: char| c.is_ascii_digit()) {
        ident.insert(0, '_');
    }
    ident
}

/// Render the generated flat-registry module.
///
/// Fails rather than emitting when the data does not fit the shape the crate
/// reads it with — an index that does not fit a `u16`, two registries that
/// mangle to one identifier. Each of those would otherwise be a table that
/// compiles and lies.
pub fn registries(data: &Registries, version: &str) -> Result<String, String> {
    let mut out = String::with_capacity(256 * 1024);

    // Stated in the header rather than left to the reader, and counted rather
    // than remembered: both are the kind of number that is true of one release
    // and quietly false of the next.
    let disagree = data
        .registries
        .iter()
        .filter(|r| r.name_order_disagrees)
        .count();
    let distinct: BTreeSet<&str> = data
        .registries
        .iter()
        .flat_map(|r| r.entries.iter())
        .map(|e| e.name.as_str())
        .collect();
    let shared = data.entry_count - distinct.len();

    let _ = writeln!(
        out,
        "// Generated by `cargo xtask extract --version {version}`. Do not edit.\n\
         //\n\
         // Derived from the registry report produced by Minecraft {version}'s own data\n\
         // generators, run against a server jar on the machine that generated this. No\n\
         // Mojang file is committed; this is the Rust that resulted from reading one.\n\
         //\n\
         // `minecraft:block` is deliberately absent. `generated::blocks` is built from a\n\
         // different report and already lists every block in protocol-id order, so a\n\
         // second table here would be a second answer to \"what is block 42\". The\n\
         // extractor checks that the two reports agree on that order before leaving the\n\
         // registry out — see `check_block_ids_match_state_order`.\n\
         //\n\
         // Each registry is three statics: its entry names in *name* order, so a lookup\n\
         // is a binary search; the protocol id of each of those, in the same order; and\n\
         // the reverse index, protocol id to position, so decoding is an array index.\n\
         // Name order is not protocol-id order for {disagree} of the {} registries here, so\n\
         // both are needed. Names are stored whole rather than interned: deduplicating\n\
         // them would merge {shared} of {} and cost `name()` its `&'static str`.\n",
        data.registries.len(),
        data.entry_count,
    );
    let _ = writeln!(out, "use crate::RegistryDef;\n");
    let _ = writeln!(
        out,
        "/// The Minecraft version this table was generated from. The blocks table\n\
         /// carries its own; a test insists they are the same, because two tables from\n\
         /// two different extraction runs would be a version skew nothing else notices."
    );
    let _ = writeln!(out, "pub const DATA_VERSION: &str = {version:?};\n");
    let _ = writeln!(
        out,
        "/// Entries across every registry in [`REGISTRIES`]. Blocks are not counted;\n\
         /// they are in [`crate::generated::blocks`]."
    );
    let _ = writeln!(
        out,
        "pub const ENTRY_COUNT: usize = {};\n",
        data.entry_count
    );

    if u8::try_from(data.registries.len()).is_err() {
        return Err(format!(
            "there are {} registries, and a Registry is a u8 index into them",
            data.registries.len()
        ));
    }

    let mut idents: BTreeMap<String, &str> = BTreeMap::new();
    for registry in &data.registries {
        let ident = registry_ident(&registry.name);
        if let Some(other) = idents.insert(ident.clone(), &registry.name) {
            return Err(format!(
                "{} and {other} both name their statics {ident}",
                registry.name
            ));
        }
    }

    for registry in &data.registries {
        emit_registry(&mut out, registry, &registry_ident(&registry.name))?;
    }

    let _ = writeln!(
        out,
        "/// Every flat registry, ordered by name, for binary search. `minecraft:block`\n\
         /// is not among them, so registry protocol ids have one hole."
    );
    let _ = writeln!(out, "pub static REGISTRIES: &[RegistryDef] = &[");
    for registry in &data.registries {
        let ident = registry_ident(&registry.name);
        let default = match &registry.default {
            Some(default) => format!("Some({default:?})"),
            None => "None".to_owned(),
        };
        let _ = writeln!(
            out,
            "    RegistryDef {{ name: {:?}, protocol_id: {}, names: {ident}_NAMES, \
             ids: {ident}_IDS, by_id: {ident}_BY_ID, default: {default} }},",
            registry.name, registry.protocol_id
        );
    }
    let _ = writeln!(out, "];\n");

    let _ = writeln!(
        out,
        "/// Each registry's position in [`REGISTRIES`].\n\
         ///\n\
         /// Generated, so a hand-written type over one registry cannot drift onto\n\
         /// another's table when a Minecraft release adds a registry and the name order\n\
         /// shifts underneath it."
    );
    let _ = writeln!(out, "pub mod index {{");
    for (position, registry) in data.registries.iter().enumerate() {
        let _ = writeln!(out, "    /// `{}`", registry.name);
        let _ = writeln!(
            out,
            "    pub const {}: usize = {position};",
            registry_ident(&registry.name)
        );
    }
    let _ = writeln!(out, "}}\n");

    registry_samples(&mut out, data);
    Ok(out)
}

fn emit_registry(out: &mut String, registry: &Registry, ident: &str) -> Result<(), String> {
    if u16::try_from(registry.entries.len()).is_err() {
        return Err(format!(
            "{} has {} entries, and the index arrays are u16",
            registry.name,
            registry.entries.len()
        ));
    }

    let _ = writeln!(
        out,
        "// {} — {} entries.",
        registry.name,
        registry.entries.len()
    );
    let _ = writeln!(out, "static {ident}_NAMES: &[&str] = &[");
    for entry in &registry.entries {
        let _ = writeln!(out, "    {:?},", entry.name);
    }
    let _ = writeln!(out, "];");

    let mut ids = Vec::with_capacity(registry.entries.len());
    // Dense 0..n, checked at parse, so every slot of the reverse index is
    // written exactly once and `u16::MAX` can never survive as a hole.
    let mut by_id = vec![u16::MAX; registry.entries.len()];
    for (position, entry) in registry.entries.iter().enumerate() {
        let id = u16::try_from(entry.protocol_id).map_err(|_| {
            format!(
                "{}: {} has protocol id {}, and the id arrays are u16",
                registry.name, entry.name, entry.protocol_id
            )
        })?;
        ids.push(id);
        by_id[id as usize] = position as u16;
    }
    write_u16_rows(out, &format!("{ident}_IDS"), &ids);
    write_u16_rows(out, &format!("{ident}_BY_ID"), &by_id);
    let _ = writeln!(out);
    Ok(())
}

fn write_u16_rows(out: &mut String, name: &str, values: &[u16]) {
    let _ = writeln!(out, "static {name}: &[u16] = &[");
    for chunk in values.chunks(16) {
        let row: Vec<String> = chunk.iter().map(u16::to_string).collect();
        let _ = writeln!(out, "    {},", row.join(", "));
    }
    let _ = writeln!(out, "];");
}

/// A golden sample of the id-to-name mapping, **taken from the report** rather
/// than from the tables above.
///
/// A flat registry has nothing that checks itself. Decoding id 963 to
/// `minecraft:diamond_sword` and encoding it back agrees with itself under any
/// bijection between names and ids, including one where every id is off by one
/// and every sword in the world is a shovel. A round-trip proves the two
/// directions of *this* table agree with each other; whether they agree with
/// Minecraft is the question, and only something that did not come from the
/// table can answer it.
///
/// Each row is `(registry, protocol_id, entry)` read straight out of the
/// report's entry map, which is keyed by name and states each name's id
/// directly. It is not sorted by this extractor, not indexed by it, and does
/// not pass through `Registry` — so a wrong sort or a shifted id changes what
/// the table decodes and leaves these rows saying what they always said.
///
/// Every registry contributes rows, so a registry cannot fall out of the
/// sample's coverage while the suite stays green.
fn registry_samples(out: &mut String, data: &Registries) {
    let _ = writeln!(
        out,
        "/// A sample of the protocol-id-to-name mapping as Mojang's report states it,\n\
         /// read from the report's own entry map rather than from the tables above.\n\
         /// Every registry is represented. See `crates/dust-registry/tests/` for why a\n\
         /// self-consistent round-trip is not enough on its own."
    );
    let _ = writeln!(out, "pub static ENTRY_SAMPLES: &[(&str, u32, &str)] = &[");
    for registry in &data.registries {
        let Some(reported) = data.reported.get(&registry.name) else {
            continue;
        };
        let wanted = registry_sample_ids(registry.entries.len() as u32);
        // Walking the report's map, not the sorted table: this row has to be
        // able to disagree with the table for it to be worth asserting.
        let mut rows: Vec<(u32, &str)> = reported
            .entries
            .iter()
            .filter(|(_, entry)| wanted.contains(&entry.protocol_id))
            .map(|(name, entry)| (entry.protocol_id, name.as_str()))
            .collect();
        rows.sort_unstable();
        for (id, name) in rows {
            let _ = writeln!(out, "    ({:?}, {id}, {name:?}),", registry.name);
        }
    }
    let _ = writeln!(out, "];");
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn a_registry_identifier_drops_minecraft_and_keeps_anything_else() {
        assert_eq!(registry_ident("minecraft:item"), "ITEM");
        assert_eq!(
            registry_ident("minecraft:worldgen/biome_source"),
            "WORLDGEN_BIOME_SOURCE"
        );
        assert_eq!(registry_ident("brigadier:thing"), "BRIGADIER_THING");
    }

    #[test]
    fn a_registry_of_one_contributes_one_sample_row() {
        assert_eq!(registry_sample_ids(1), vec![0]);
        assert_eq!(registry_sample_ids(2), vec![0, 1]);
    }

    #[test]
    fn a_sample_covers_both_ends_and_the_middle() {
        assert_eq!(registry_sample_ids(100), vec![0, 1, 25, 50, 75, 99]);
    }
}
