//! Emitting the block table as Rust.
//!
//! What lands in the repository is this generated Rust, not Mojang's JSON. The
//! project's Code Provenance document draws that line: the extractor and the
//! generated code are the repository's; Mojang's files stay on the machine that
//! downloaded them.

use std::collections::BTreeMap;
use std::fmt::Write as _;

use super::blocks::{Blocks, ReportedBlock};

/// Every block with properties contributes at least these offsets from its base
/// id to the golden sample.
///
/// Offset 1 is the sharp one: it must differ from the base state in exactly the
/// *last* property, so it fails immediately if the wrong property was decided
/// to vary fastest. The other two spread the check across the range so an error
/// in a middle digit is caught as well.
fn sample_offsets(state_count: u32) -> Vec<u32> {
    let mut offsets = vec![0, 1, state_count / 2, state_count - 1];
    offsets.retain(|o| *o < state_count);
    offsets.sort_unstable();
    offsets.dedup();
    offsets
}

/// Render the generated block module.
pub fn blocks(data: &Blocks, version: &str, reported: &BTreeMap<String, ReportedBlock>) -> String {
    let mut out = String::with_capacity(512 * 1024);

    let _ = writeln!(
        out,
        "// Generated by `cargo xtask extract --version {version}`. Do not edit.\n\
         //\n\
         // Derived from the block report produced by Minecraft {version}'s own data\n\
         // generators, run against a server jar on the machine that generated this. No\n\
         // Mojang file is committed; this is the Rust that resulted from reading one.\n\
         //\n\
         // The property order in each entry is the *state id* order — the first property\n\
         // varies slowest — which is derived from the ids rather than taken from the\n\
         // report's key order, because for four blocks on 1.21.1 those disagree.\n"
    );
    let _ = writeln!(out, "use crate::{{BlockDef, PropertyDef}};\n");
    let _ = writeln!(
        out,
        "/// The Minecraft version this table was generated from."
    );
    let _ = writeln!(out, "pub const DATA_VERSION: &str = {version:?};\n");
    let _ = writeln!(
        out,
        "/// The number of distinct block states, so `0..STATE_COUNT` is every"
    );
    let _ = writeln!(out, "/// id that decodes to something.");
    let _ = writeln!(out, "pub const STATE_COUNT: u32 = {};\n", data.state_count);

    // Value lists repeat heavily — every `facing` with the same six values, every
    // boolean — so they are interned. It roughly halves the file, and a file
    // that appears in every diff of this table is worth keeping small.
    let mut interned: BTreeMap<Vec<String>, String> = BTreeMap::new();
    let mut value_lists = String::new();
    for block in &data.blocks {
        for property in &block.properties {
            if interned.contains_key(&property.values) {
                continue;
            }
            let name = format!("V{}", interned.len());
            let rendered: Vec<String> = property.values.iter().map(|v| format!("{v:?}")).collect();
            let _ = writeln!(
                value_lists,
                "static {name}: &[&str] = &[{}];",
                rendered.join(", ")
            );
            interned.insert(property.values.clone(), name);
        }
    }
    let _ = writeln!(out, "{value_lists}");

    let _ = writeln!(out, "/// Every block, ordered by base state id.");
    let _ = writeln!(out, "pub static BLOCKS: &[BlockDef] = &[");
    for block in &data.blocks {
        let properties: Vec<String> = block
            .properties
            .iter()
            .map(|p| {
                format!(
                    "PropertyDef {{ name: {:?}, values: {} }}",
                    p.name, interned[&p.values]
                )
            })
            .collect();
        let _ = writeln!(
            out,
            "    BlockDef {{ name: {:?}, base_state_id: {}, state_count: {}, \
             default_state_id: {}, properties: &[{}] }},",
            block.name,
            block.base_state_id,
            block.state_count,
            block.default_state_id,
            properties.join(", ")
        );
    }
    let _ = writeln!(out, "];\n");

    // Names are wanted in alphabetical order for lookup and in state-id order
    // for decoding, and one table cannot be both. This is the index that makes
    // a name lookup a binary search instead of a scan of 1,060 strings.
    let mut by_name: Vec<(usize, &str)> = data
        .blocks
        .iter()
        .enumerate()
        .map(|(i, b)| (i, b.name.as_str()))
        .collect();
    by_name.sort_by_key(|(_, name)| *name);
    let _ = writeln!(
        out,
        "/// Indices into [`BLOCKS`], ordered by name, for binary search."
    );
    let _ = writeln!(out, "pub static BLOCKS_BY_NAME: &[u16] = &[");
    for chunk in by_name.chunks(16) {
        let row: Vec<String> = chunk.iter().map(|(i, _)| i.to_string()).collect();
        let _ = writeln!(out, "    {},", row.join(", "));
    }
    let _ = writeln!(out, "];\n");

    samples(&mut out, data, reported);
    out
}

/// A golden sample of the id-to-properties mapping, **taken from the report**
/// rather than from the table above.
///
/// This exists because the round-trip test in `dust-registry` cannot catch the
/// defect this extractor is most likely to have. Decoding a state through the
/// table and re-encoding it through the same table agrees with itself under
/// *any* internally consistent property order, including a wrong one — so a
/// round-trip proves the encoder and the decoder agree with each other, which
/// is not the question. The question is whether they agree with Minecraft, and
/// only something derived independently of the derived order can answer it.
///
/// Each row is `(id, block, "key=value,...")` with the keys sorted
/// **alphabetically**, which deliberately encodes nothing about the radix
/// order. If the property order is wrong, the values decoded for a given id
/// change, and these rows stop matching.
///
/// Every block that has properties contributes rows, so coverage is per block
/// rather than a stride across the id space — a stride misses whole blocks, and
/// a block is the unit the order is decided for.
fn samples(out: &mut String, data: &Blocks, reported: &BTreeMap<String, ReportedBlock>) {
    let _ = writeln!(
        out,
        "/// A sample of the id-to-properties mapping as Mojang\'s report states it,\n\
         /// with property names sorted alphabetically so that nothing here encodes\n\
         /// the order the ids actually use. Every block with properties is\n\
         /// represented. See `crates/dust-registry/tests/` for why a self-consistent\n\
         /// round-trip is not enough on its own."
    );
    let _ = writeln!(out, "pub static STATE_SAMPLES: &[(u32, &str, &str)] = &[");

    let mut rows = Vec::new();
    for block in &data.blocks {
        let Some(report) = reported.get(&block.name) else {
            continue;
        };
        if block.properties.is_empty() {
            continue;
        }
        let wanted: Vec<u32> = sample_offsets(block.state_count)
            .iter()
            .map(|o| block.base_state_id + o)
            .collect();
        for state in &report.states {
            if !wanted.contains(&state.id) {
                continue;
            }
            // BTreeMap iterates in key order, which is the alphabetical
            // ordering this row depends on being independent of the radix.
            let pairs: Vec<String> = state
                .properties
                .iter()
                .map(|(k, v)| format!("{k}={v}"))
                .collect();
            rows.push((state.id, block.name.clone(), pairs.join(",")));
        }
    }
    rows.sort_by_key(|(id, _, _)| *id);
    for (id, name, properties) in &rows {
        let _ = writeln!(out, "    ({id}, {name:?}, {properties:?}),");
    }
    let _ = writeln!(out, "];");
}
