//! Hand-built binary fixtures, and the two dialects fed to each other.
//!
//! # Why bytes written by hand when a round-trip suite exists
//!
//! `tests/roundtrip.rs` proves the reader and writer agree with each other;
//! these fixtures pin what they agree **to**. Every byte in them was worked out
//! from the format — id, then name, then big-endian payload — not generated by
//! the code under test, so flipping an encoder convention (endian, prefix
//! width, the two-byte NUL) fails here even though every round-trip stays
//! green. The second half of the file is about the dialects: file form and
//! network form differ by the root name's presence, and each is exactly one
//! plausible misreading away from the other. Those failure modes are proved
//! here on purpose, with the bytes spelled out, because "the modes are
//! incompatible" is a rumour until you have seen what each confusion actually
//! does.

mod support;

use dust_nbt::{read, write, Compound, Limits, Mode, Named, Tag, TagType};

/// A compound holding one byte field, both ways, as raw hex.
///
/// This is the fixture everything else is calibrated against: if these twelve
/// and seven bytes are not what this crate writes, the rest of the file is
/// answering a different question.
#[test]
fn a_one_field_compound_is_these_exact_bytes() {
    let mut compound = Compound::new();
    compound.insert("x", Tag::Byte(7));

    let file = write::to_vec("", &Tag::Compound(compound.clone())).expect("writes");
    assert_eq!(
        file,
        vec![0x0a, 0x00, 0x00, 0x01, 0x00, 0x01, 0x78, 0x07, 0x00],
        "id 0a, empty name, field TAG_Byte named x, payload 07, TAG_End"
    );

    let network = write::to_vec_network(Some(&Tag::Compound(compound))).expect("writes");
    assert_eq!(
        network,
        vec![0x0a, 0x01, 0x00, 0x01, 0x78, 0x07, 0x00],
        "the same document without the two name-length bytes"
    );
}

/// Every scalar width against bytes worked out by hand, read and written.
#[test]
fn scalar_widths_are_big_endian_and_signed() {
    let mut compound = Compound::new();
    compound.insert("b", Tag::Byte(-1));
    compound.insert("s", Tag::Short(-2));
    compound.insert("i", Tag::Int(-3));
    compound.insert("l", Tag::Long(-4));
    compound.insert("f", Tag::Float(1.0));
    compound.insert("d", Tag::Double(-2.0));

    let bytes = write::to_vec("", &Tag::Compound(compound.clone())).expect("writes");
    let expected: Vec<u8> = [
        &[
            0x0a, 0x00, 0x00, //
            0x01, 0x00, 0x01, b'b', 0xff, //
            0x02, 0x00, 0x01, b's', 0xff, 0xfe, //
            0x03, 0x00, 0x01, b'i', 0xff, 0xff, 0xff, 0xfd, //
            0x04, 0x00, 0x01, b'l', 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xfc, //
            0x05, 0x00, 0x01, b'f', 0x3f, 0x80, 0x00, 0x00, //
            0x06, 0x00, 0x01, b'd', 0xc0, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, //
            0x00,
        ][..],
    ]
    .concat();
    assert_eq!(bytes, expected, "payloads are two's complement and IEEE 754 big-endian");

    // And the same bytes are *read back* into the same tags, so the check does
    // not depend on the writer having been the one to produce them.
    let document = read::from_bytes_exact(&expected).expect("reads");
    assert_eq!(document.tag, Tag::Compound(compound));
}

/// A string through the whole stack: NUL as `c0 80`, section sign as two
/// bytes, an emoji as a surrogate pair — and byte-identical on rewrite.
#[test]
fn a_string_through_the_stack_stays_byte_identical() {
    let text = "a\u{0000}b\u{00a7}c\u{1f600}";
    let bytes = write::to_vec("", &Tag::String(text.to_owned())).expect("writes");

    let payload: Vec<u8> = [
        &[0x00, 13u8][..], // the length prefix: encoded_len counts six for the pair
        &[0x61],           // a
        &[0xc0, 0x80],     // U+0000, never a bare 00
        &[0x62],           // b
        &[0xc2, 0xa7],     // §
        &[0x63],           // c
        &[0xed, 0xa0, 0xbd, 0xed, 0xb8, 0x80], // U+1F600 as two three-byte halves
    ]
    .concat();
    assert_eq!(payload.len(), 15);
    let mut expected = vec![0x08, 0x00, 0x00];
    expected.extend_from_slice(&payload);
    // Skip the root id and name; compare the payload the length prefix describes.
    assert_eq!(&bytes[3..], &payload[..]);
    assert_eq!(&bytes[3..5], &[0x00, 0x0d][..], "the u16 prefix counts encoded bytes");

    let document = read::from_bytes_exact(&bytes).expect("reads");
    assert_eq!(document.tag, Tag::String(text.to_owned()));
}

/// Exactly 65,535 encoded bytes fills the `u16` prefix; there is no 65,536th.
#[test]
fn the_string_length_prefix_boundary_is_exactly_u16_max() {
    use dust_nbt::mutf8;

    let at_limit: String = std::iter::repeat_n('x', mutf8::MAX_ENCODED_LEN).collect();
    let bytes = write::to_vec("", &Tag::String(at_limit.clone())).expect("writes");
    // Root id, empty root name, then the payload's own `ff ff` prefix.
    assert_eq!(&bytes[1..3], &[0x00, 0x00][..]);
    assert_eq!(&bytes[3..5], &[0xff, 0xff][..]);
    assert!(read::from_bytes_exact(&bytes).is_ok());

    let over: String = std::iter::repeat_n('x', mutf8::MAX_ENCODED_LEN + 1).collect();
    assert!(write::to_vec("", &Tag::String(over)).is_err());
}

/// An empty list keeps whatever element type it declared, vanilla's or
/// otherwise, and rewriting preserves it either way.
#[test]
fn an_empty_lists_declared_type_survives_a_rewrite() {
    // Vanilla writes TAG_End (0) as the element type of an empty list. Root
    // id, empty root name, element type, then a zero length: eight bytes.
    let vanilla_wrote = [0x09, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00];
    let document = read::from_bytes_exact(&vanilla_wrote).expect("reads");
    let Tag::List(list) = &document.tag else {
        panic!("a list went in")
    };
    assert_eq!(list.element_type(), TagType::End);
    assert_eq!(
        write::to_vec("", &document.tag).expect("rewrites"),
        vanilla_wrote.to_vec(),
        "vanilla's spelling comes back unchanged"
    );

    // Another tool may declare Int (3) for its empty list. Reading it must not
    // "fix" it to End, or the rewrite differs from the input.
    let other_wrote = [0x09, 0x00, 0x00, 0x03, 0x00, 0x00, 0x00, 0x00];
    let document = read::from_bytes_exact(&other_wrote).expect("reads");
    let Tag::List(list) = &document.tag else {
        panic!("a list went in")
    };
    assert_eq!(list.element_type(), TagType::Int);
    assert_eq!(
        write::to_vec("", &document.tag).expect("rewrites"),
        other_wrote.to_vec(),
        "a declared type from another tool survives"
    );
}

/// Duplicate keys are kept, in order, and resolve to the last binding.
#[test]
fn duplicate_keys_are_preserved_and_resolve_to_the_last() {
    // {id: "first", id: "second"} with both bindings intact.
    let bytes: Vec<u8> = [
        &[
            0x0a, 0x00, 0x00, //
            0x08, 0x00, 0x01, b'a', 0x00, 0x05, b'f', b'i', b'r', b's', b't', //
            0x08, 0x00, 0x01, b'a', 0x00, 0x06, b's', b'e', b'c', b'o', b'n', b'd', //
            0x00,
        ][..],
    ]
    .concat();

    let document = read::from_bytes_exact(&bytes).expect("reads");
    let compound = document.tag.as_compound().expect("a compound");
    assert_eq!(compound.len(), 2, "both bindings stay in the document");
    assert_eq!(
        compound.get("a").and_then(Tag::as_str),
        Some("second"),
        "the last binding wins, like Java's HashMap.put leaves it"
    );
    assert_eq!(
        write::to_vec("", &document.tag).expect("rewrites"),
        bytes,
        "a rewrite preserves both bindings, in order"
    );
}

// ---------------------------------------------------------------------------
// Refusals, each naming where it stopped
// ---------------------------------------------------------------------------

/// The malformed inputs a hostile packet starts with, refused with the error
/// that names the trouble rather than a panic or a wrong document.
#[test]
fn malformed_documents_are_refused_with_precise_errors() {
    use dust_nbt::Error;

    // Tag id 13 does not exist.
    assert_eq!(
        read::from_bytes(&[0x0d, 0x00]).map(|n| n.tag),
        Err(Error::UnknownTagId { offset: 0, id: 13 })
    );

    // The root cannot be TAG_End: network mode spells absence differently.
    assert_eq!(
        read::from_bytes(&[0x00]),
        Err(Error::UnexpectedEndTag {
            offset: 0,
            context: "the root tag of a document",
        })
    );

    // A negative array length is representable and refused.
    assert_eq!(
        read::from_bytes(&[
            0x07, 0x00, 0x00, // TAG_Byte_Array, empty name
            0xff, 0xff, 0xff, 0xff, // length -1
        ])
        .map(|n| n.tag),
        Err(Error::NegativeLength {
            offset: 3,
            length: -1,
            tag: TagType::ByteArray,
        })
    );

    // A list claiming more elements than the input could hold is refused by
    // arithmetic, before any allocation.
    let claimed = i32::to_be_bytes(1_000_000);
    let mut lying = vec![0x09, 0x00, 0x00];
    lying.extend_from_slice(&[0x0a]); // compounds, one byte each at minimum
    lying.extend_from_slice(&claimed);
    lying.push(0x00);
    match read::from_bytes(&lying).map(|n| n.tag) {
        Err(Error::LengthExceedsInput {
            claimed,
            available,
            ..
        }) => {
            assert_eq!(claimed, 1_000_000);
            assert_eq!(available, 1);
        }
        other => panic!("expected LengthExceedsInput, got {other:?}"),
    }

    // A list whose element type is TAG_End but which claims an element has no
    // type to read it as.
    assert!(matches!(
        read::from_bytes(&[0x09, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0x01]).map(|n| n.tag),
        Err(Error::UnexpectedEndTag {
            context: "the element type of a list that claims elements",
            ..
        })
    ));

    // Truncation mid-payload names how many bytes were missing.
    assert!(matches!(
        read::from_bytes(&[0x03, 0x00, 0x00, 0x12]),
        Err(Error::UnexpectedEnd { needed: 4, available: 1, .. })
    ));
}

/// Bytes after a complete document are padding, not an error — unless the
/// caller asks, which is what `exact` is for and what `position` reports.
#[test]
fn trailing_padding_is_tolerated_then_reported() {
    let document_bytes = write::to_vec("", &Tag::Byte(-7)).expect("writes");
    let mut padded = document_bytes.clone();
    padded.extend(std::iter::repeat_n(0u8, 4096 - padded.len()));

    // Plain reading stops where the document ends; a region-file reader uses
    // that number to find the next slot boundary.
    let document = read::from_bytes(&padded).expect("reads past padding");
    assert_eq!(document.tag, Tag::Byte(-7));

    let mut reader = read::Reader::new(&padded, Limits::default());
    let named = reader.read_root(Mode::File).expect("reads");
    assert_eq!(named, Named {
        name: String::new(),
        tag: Tag::Byte(-7)
    });
    assert_eq!(reader.position(), document_bytes.len());
    assert!(reader.finish().is_err(), "padding is still there");
}

// ---------------------------------------------------------------------------
// Mode confusion, on purpose
//
// `read::Mode`'s doc comment argues that guessing the dialect from the bytes
// is attacker-selectable. These tests are that argument, carried out: each
// direction of confusion is fed real bytes and the outcome recorded as an
// assertion, so the claim cannot quietly stop being true.
// ---------------------------------------------------------------------------

/// File-form bytes pushed through the network reader parse *successfully and
/// wrongly*. The root name's length prefix is indistinguishable from payload,
/// so a named root becomes a different value plus trailing bytes the network
/// entry point is contractually allowed to ignore. This is why the caller —
/// who knows where the bytes came from — picks the mode, and why a network
/// consumer bounds its input upstream instead of trusting `finish()`.
#[test]
fn file_bytes_through_the_network_reader_succeed_and_are_wrong() {
    let file_form = write::to_vec("hi", &Tag::Byte(7)).expect("writes");
    assert_eq!(file_form, vec![0x01, 0x00, 0x02, 0x68, 0x69, 0x07]);

    // Network reading takes `00` — the high half of the name length — as the
    // whole payload, and stops. No error. Wrong value.
    let misread = read::from_bytes_network(&file_form)
        .expect("no error: that is the finding")
        .expect("not the absent-NBT byte");
    assert_eq!(misread, Tag::Byte(0), "the payload became zero, not seven");
    assert_ne!(misread, Tag::Byte(7));

    // An empty-name compound reads as an empty compound — right-shaped, wrong
    // size, with the entire original body left behind as trailing bytes.
    let body = write::to_vec("", &Tag::Compound({
        let mut c = Compound::new();
        c.insert("x", Tag::Byte(7));
        c
    }))
    .expect("writes");
    let misread = read::from_bytes_network(&body)
        .expect("still no error")
        .expect("still not absent");
    assert_eq!(
        misread,
        Tag::Compound(Compound::new()),
        "the fields vanished behind the name prefix"
    );
    let mut reader = read::Reader::new(&body, Limits::NETWORK);
    let _ = reader.read_root(Mode::Network).expect("reads");
    assert!(
        reader.finish().is_err(),
        "only the caller-side trailing check notices anything happened"
    );
}

/// Network-form bytes pushed through the file reader fail — for now. The two
/// bytes after the root id are read as a name length the sender chose, so the
/// reader demands a name the input does not contain. With a longer crafted
/// input the demand *is* satisfiable, which is the attacker-selectable case:
/// the same bytes are a complete document in one dialect and a different
/// complete document in the other.
#[test]
fn network_bytes_through_the_file_reader_fail_or_read_as_something_else() {
    // The empty network compound, 0a 00: the file reader wants a two-byte name
    // length and has one byte.
    assert!(matches!(
        read::from_bytes(&[0x0a, 0x00]),
        Err(dust_nbt::Error::UnexpectedEnd {
            while_reading: "a string's length prefix",
            ..
        })
    ));

    // A network compound with a field: the field's own name prefix supplies
    // the file reader's root-name length, here `01 00` = 256 bytes.
    let network = write::to_vec_network(Some(&Tag::Compound({
        let mut c = Compound::new();
        c.insert("x", Tag::Byte(7));
        c
    })))
    .expect("writes");
    assert!(matches!(
        read::from_bytes(&network),
        Err(dust_nbt::Error::UnexpectedEnd {
            needed: 256,
            while_reading: "a string payload",
            ..
        })
    ));

    // And the selectable case, constructed directly. Read as a file: a
    // complete document, root named "A" with one field y=Byte(7), nothing
    // left over. Read as a network document: an empty compound with eight
    // trailing bytes. Same bytes, two documents, and only the caller knows
    // which one is real.
    let ambiguous: [u8; 10] = [0x0a, 0x00, 0x01, 0x41, 0x01, 0x00, 0x01, 0x79, 0x07, 0x00];

    let as_file = read::from_bytes_exact(&ambiguous).expect("file reading succeeds completely");
    assert_eq!(as_file.name, "A");
    let expected_file = {
        let mut c = Compound::new();
        c.insert("y", Tag::Byte(7));
        Tag::Compound(c)
    };
    assert_eq!(as_file.tag, expected_file);

    let as_network = read::from_bytes_network(&ambiguous)
        .expect("network reading also succeeds")
        .expect("not absent");
    assert_eq!(as_network, Tag::Compound(Compound::new()));
    assert_ne!(as_file.tag, as_network, "the readings disagree, silently");
}
