//! Generates `docs/configuration.md` from the configuration types.
//!
//! The reference is generated rather than written because a reference that is
//! written by hand is a reference that is wrong — not immediately, but by the
//! third setting somebody adds in a hurry. `just verify` regenerates it and
//! fails if the file on disk differs, so the documentation and the types move
//! in the same commit or not at all.

use std::fmt::Write as _;

use crate::{ConfigSection, DustConfig, SectionDoc};

/// The header on the generated file, so nobody edits it by hand twice.
const PREAMBLE: &str = "\
<!-- Generated by `cargo xtask docs`. Do not edit by hand: your changes will be
     overwritten, and `just verify` will fail before they ever reach anyone.
     Edit the doc comments on the types in `crates/dust-config/src/` instead. -->

# Dust — configuration reference

Every setting Dust has, with its default and when a change to it takes effect.

Settings are read from `dust.toml`, then overridden by environment variables
named `DUST__SECTION__FIELD` (two underscores between path segments, because one
is a legal character inside a setting name), then by runtime commands.

The **when** column says what a change does:

| | |
| --- | --- |
| `hot` | Takes effect on reload. |
| `hot, new chunks only` | Takes effect on reload, for terrain generated from then on. Chunks already on disk are not regenerated and do not change. |
| `restart` | Read once at startup. |
";

/// Render the whole reference.
pub fn render() -> String {
    let mut out = String::from(PREAMBLE);
    let root = DustConfig::describe();
    for section in &root.subsections {
        render_section(&mut out, section, "");
    }
    out
}

fn render_section(out: &mut String, section: &SectionDoc, prefix: &str) {
    let path = if prefix.is_empty() {
        section.key.to_owned()
    } else {
        format!("{prefix}.{}", section.key)
    };

    let heading = match section.keyed_by {
        Some(label) => format!("[{path}.<{}>]", label.replace(' ', "-")),
        None => format!("[{path}]"),
    };
    let _ = writeln!(out, "\n## `{heading}`\n");
    let _ = writeln!(out, "{}\n", section.doc);

    if !section.fields.is_empty() {
        let _ = writeln!(out, "| Setting | Type | Default | When | Meaning |");
        let _ = writeln!(out, "| --- | --- | --- | --- | --- |");
        for field in &section.fields {
            let _ = writeln!(
                out,
                "| `{}` | `{}` | `{}` | {} | {} |",
                field.name,
                field.ty,
                field.default,
                field.reload.label(),
                field.doc.replace('\n', " ").replace('|', "\\|"),
            );
        }
    }

    for sub in &section.subsections {
        render_section(out, sub, &path);
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn every_setting_appears_in_the_reference() {
        // The Phase 0.3 exit criterion has two halves. The compiler enforces
        // the first — a field with no doc comment does not build. This is the
        // second: a documented field that the generator silently drops would
        // pass that check and still ship undocumented.
        let rendered = render();
        let mut missing = Vec::new();
        walk(&DustConfig::describe(), &mut |section, path| {
            for field in &section.fields {
                let entry = format!("| `{}` |", field.name);
                if !rendered.contains(&entry) {
                    missing.push(format!("{path}.{}", field.name));
                }
            }
        });
        assert!(
            missing.is_empty(),
            "settings missing from the reference: {missing:?}"
        );
    }

    fn walk(section: &SectionDoc, f: &mut impl FnMut(&SectionDoc, &str)) {
        fn inner(section: &SectionDoc, prefix: &str, f: &mut impl FnMut(&SectionDoc, &str)) {
            let path = if prefix.is_empty() {
                section.key.to_owned()
            } else {
                format!("{prefix}.{}", section.key)
            };
            f(section, &path);
            for sub in &section.subsections {
                inner(sub, &path, f);
            }
        }
        inner(section, "", f);
    }
}
