//! `harness rewrite` — Phase 2's exit criterion, as a command.
//!
//! > *Dust loads a world generated by a vanilla server, serves it to a client
//! > that sees identical terrain and lighting, saves it, and vanilla reopens it
//! > without complaint.*
//!
//! The first two clauses are checked by `dust-world`'s own tests and by a
//! client standing in the world. The last two cannot be: no test written here
//! can say whether a file is one Minecraft accepts, because the only authority
//! on that is Minecraft. So this verb goes and asks it.
//!
//! ```text
//! 1. copy   seed-<n>/ to seed-<n>-rewritten/, world and all
//! 2. rewrite every chunk of every region file through dust-world's
//!    reader and writer — the server's real code, not a copy of it
//! 3. boot   vanilla on the copy and let it load, relight and resave
//! 4. digest what vanilla wrote, with the harness's own independent reader
//! 5. diff   that against the capture of the world it started as
//! ```
//!
//! # Why the digest is not the whole check
//!
//! **Vanilla does not fail on a chunk it cannot read.** It logs, discards it,
//! and regenerates it from the seed — so the server boots normally, the capture
//! completes, and the harness is handed a whole world with nothing to say that
//! anything went wrong. Measured, by scrambling 200 bytes of one chunk's
//! compressed payload and leaving the region header intact: vanilla logged
//! `Failed to read chunk [0, 0]`, `Failed to load chunk 0,0` and two more, and
//! then printed `Done (4.392s)!` and ran.
//!
//! So the criterion's own words are checked separately: *without complaint*.
//! Everything vanilla says during a capture is kept (`<capture>/server.log`),
//! and this verb compares the transcript of the run over Dust's world against
//! the transcript of the run over the world vanilla wrote itself. **Anything
//! the second run said that the first did not is a finding.** That is a
//! differential rather than a list of known-bad strings — deliberately, because
//! a list can only fail on the cases whoever wrote it already thought of, and
//! the interesting failure is always the other kind.
//!
//! In that particular experiment the digest would have caught it too: the
//! regenerated chunk came back `minecraft:full` but with 26 distinct block
//! names where the original had 28, because regenerating one chunk into a world
//! whose neighbours are already finished loses the decoration those neighbours
//! would have contributed. That is worth stating precisely rather than
//! overclaiming — the two checks overlap here.
//!
//! Where they do **not** overlap is the failure this writer can actually cause.
//! The digest covers blocks, biomes and heightmaps and nothing else. A carried
//! block entity whose block Dust has since broken is a record vanilla drops as
//! invalid and logs about, and every block in the chunk is still exactly where
//! it was. No digest in this harness would show it. The transcript is the only
//! half of the verdict that can.
//!
//! # What a green run proves, and what it does not
//!
//! Green means vanilla opened every chunk Dust wrote without saying anything
//! new about it, and the blocks, biomes and heightmaps it read back are the
//! ones the original world had.
//!
//! It does not prove the file is byte-identical to one vanilla would write, and
//! it is not meant to. Dust deliberately writes `isLightOn = 0` and no light
//! arrays (see `dust_world::anvil::write`), so the two files differ by
//! construction — and the digest is blind to light for exactly the reason the
//! writer omits it: light is an engine's output, and comparing two engines is a
//! different question from comparing two worlds.
//!
//! **And it proves that nothing was lost only as far as the transcript reaches.**
//! A digest covers blocks, biomes and heightmaps, so a rewrite that dropped
//! every chest in the world would digest clean — which is why
//! [`dust_world::anvil::write::Carried`] exists, why this verb counts what it
//! carried and prints the number, and why the transcript half is not optional.
//! A run that carries zero block entities through a world known to have some is
//! a finding, not a pass.
//!
//! # Why the source world is copied rather than rewritten in place
//!
//! Because the comparison needs the original to still exist, and because a
//! rewrite that goes wrong should cost a copy rather than the world it took
//! seven minutes to generate. The copy is also what makes the run repeatable:
//! the second `rewrite` starts from the same bytes as the first.

use std::path::{Path, PathBuf};
use std::process::ExitCode;
use std::time::{Duration, Instant};

use dust_nbt::Tag;
use dust_server::net::source::RegistryNames;
use dust_world::anvil::{self, write::Carried};
use dust_world::coords::{ChunkPos, RegionPos};
use dust_world::heightmap::WorldHeight;
use dust_world::region::{ChunkPayload, Compression, RegionFile};

use super::{cache, capture, compare, digest, properties};

/// The suffix a rewritten run directory gets. A sibling of the source rather
/// than a subdirectory of it, so that nothing vanilla writes into the copy can
/// reach the world being compared against.
const REWRITTEN_SUFFIX: &str = "-rewritten";

#[derive(Debug)]
pub struct Options {
    pub version: String,
    pub seed: i64,
    /// The same radius the baseline capture used. Not a free parameter: the
    /// diff is against that capture, and comparing different chunk sets would
    /// report every chunk one set has and the other does not as a divergence.
    pub radius: i32,
    pub jar: Option<PathBuf>,
    pub timeout: Duration,
}

/// Parse the `harness rewrite` argument list.
///
/// Delegated to [`capture::parse`], because the two verbs take the same five
/// options and a second parser would be a second place for a default to drift.
/// The cost is that a malformed flag is reported as an unknown *capture*
/// option; the usage text printed beside it covers both verbs, and one wrong
/// noun in an error message is cheaper than two parsers that disagree about
/// `--radius`.
pub fn parse(args: &[String]) -> Result<Options, String> {
    let inner = capture::parse(args)?;
    Ok(Options {
        version: inner.version,
        seed: inner.seed,
        radius: inner.radius,
        jar: inner.jar,
        timeout: inner.timeout,
    })
}

/// Run the whole loop, returning the same exit codes `compare` does: 0 the
/// worlds match, 1 they differ, 2 the run could not happen.
///
/// A difference is a **finding and not a crash**, which is why it is an exit
/// code rather than an error: the operator wants the per-chunk table, and a
/// verb that returned `Err` here would print one line and throw the table away.
pub fn run(options: &Options) -> ExitCode {
    match attempt(options) {
        Ok(code) => code,
        Err(message) => {
            eprintln!("rewrite: {message}");
            ExitCode::from(2)
        }
    }
}

fn attempt(options: &Options) -> Result<ExitCode, String> {
    let started = Instant::now();
    let layout = cache::Layout::resolve()?;
    let source = layout.server_dir(&options.version, options.seed);
    if !source.is_dir() {
        return Err(format!(
            "{} does not exist; run `harness provision --version {} --seed {} --yes` \
             and then `harness capture --version {} --seed {} --radius {}` first",
            source.display(),
            options.version,
            options.seed,
            options.version,
            options.seed,
            options.radius
        ));
    }
    if !properties::eula_accepted(&source)? {
        return Err(format!(
            "the EULA is not accepted in {}; read it, then accept it with \
             `harness provision --yes`",
            source.display()
        ));
    }

    let baseline_label =
        capture::capture_label(&options.version, options.seed, options.radius, &[(0, 0)]);
    let baseline_bin = layout.capture_dir(&baseline_label).join("chunks.bin");
    // Read before anything is copied or booted. The baseline is the thing this
    // whole run is measured against, and finding it missing after seven minutes
    // of vanilla is a worse way to learn it is not there.
    let baseline = digest::read_bin(&baseline_bin).map_err(|e| {
        format!(
            "{e}\n\nthe baseline capture is what a rewrite is compared against; make it with \
             `harness capture --version {} --seed {} --radius {}`",
            options.version, options.seed, options.radius
        )
    })?;

    let target = with_suffix(&source, REWRITTEN_SUFFIX);
    println!("copying {} to {}", source.display(), target.display());
    if target.exists() {
        std::fs::remove_dir_all(&target)
            .map_err(|e| format!("could not clear {}: {e}", target.display()))?;
    }
    copy_tree(&source, &target)?;

    let names = RegistryNames::new()
        .ok_or("the synced biome registry is missing; the build's extracted data is incomplete")?;
    let report = rewrite_world(&target.join("world/region"), &names)?;
    println!(
        "rewrote {} chunks in {} region files: {} block entities, {} block ticks and \
         {} fluid ticks carried through",
        report.chunks,
        report.regions,
        report.block_entities,
        report.block_ticks,
        report.fluid_ticks
    );
    if report.chunks == 0 {
        return Err(format!(
            "no chunks were rewritten under {}; there is nothing here to hand to vanilla",
            target.join("world/region").display()
        ));
    }

    let label = format!("{baseline_label}{REWRITTEN_SUFFIX}");
    let jar = match &options.jar {
        Some(path) => path.clone(),
        None => crate::extract::download::server_jar(&options.version, &layout.jars)?,
    };
    let inner = capture::Options {
        version: options.version.clone(),
        seed: options.seed,
        radius: options.radius,
        centres: vec![(0, 0)],
        jar: Some(jar.clone()),
        timeout: options.timeout,
    };
    capture::capture_from(&inner, &jar, &target, &label, &layout, started)?;

    let rewritten = digest::read_bin(&layout.capture_dir(&label).join("chunks.bin"))?;
    let diff = compare::diff(&baseline, &rewritten);
    print!("{}", compare::render_tsv(&diff));
    println!("{}", compare::summary_line(&diff));

    let complaints = new_messages(
        &layout.capture_dir(&baseline_label).join("server.log"),
        &layout.capture_dir(&label).join("server.log"),
    );
    match &complaints {
        Ok(lines) if lines.is_empty() => {
            println!("vanilla said nothing about Dust's world it did not say about its own");
        }
        Ok(lines) => {
            println!(
                "\n{} thing(s) vanilla said only about Dust's world:",
                lines.len()
            );
            for line in lines {
                println!("  {line}");
            }
        }
        // A transcript that is not there is a run made before this verb kept
        // them. Announced rather than silently skipped: the digest half of the
        // verdict does not stand on its own, and a reader has to know which
        // halves ran.
        Err(why) => println!("\nthe transcripts could not be compared: {why}"),
    }

    let quiet = matches!(&complaints, Ok(lines) if lines.is_empty());
    if diff.is_identical() && quiet {
        println!(
            "\nvanilla reopened every chunk Dust wrote without complaint, and read back the \
             world it started as."
        );
        return Ok(ExitCode::SUCCESS);
    }
    if !diff.is_identical() {
        println!(
            "\nthe world vanilla read back is not the world it wrote. The rows above name \
             which chunks and which of blocks, biomes or heightmaps differ."
        );
    }
    if !quiet {
        println!(
            "\nvanilla had something to say about the world Dust wrote that it did not say \
             about its own. Note that a chunk it refuses is discarded and regenerated rather \
             than reported as a failure, and that the digests cover blocks, biomes and \
             heightmaps and nothing else — so a clean diff above does not make these lines \
             harmless."
        );
    }
    Ok(ExitCode::from(1))
}

/// Messages the second transcript carries that the first does not.
///
/// Compared as *shapes* rather than as lines. A vanilla log line is a
/// timestamp, a thread name and a message, and all three vary between two runs
/// of the same thing — the clock moves, worker threads are numbered by
/// scheduling, and progress lines count. So each line is reduced to its
/// severity and its message with every run of digits replaced, and the
/// comparison is over the set of those.
///
/// **What this trades away.** Two complaints about different chunks reduce to
/// one shape, so a run is told *what* vanilla objected to and not *how often*.
/// That is the right way round: the transcripts are printed in full beside the
/// digests, and the question this answers is whether there is anything new to
/// go and read.
fn new_messages(baseline: &Path, rewritten: &Path) -> Result<Vec<String>, String> {
    let known: std::collections::HashSet<String> = read_lines(baseline)?
        .into_iter()
        .map(|line| shape_of(&line))
        .collect();
    let mut seen = std::collections::HashSet::new();
    let mut out = Vec::new();
    for line in read_lines(rewritten)? {
        let shape = shape_of(&line);
        if !known.contains(&shape) && seen.insert(shape) {
            out.push(line);
        }
    }
    Ok(out)
}

fn read_lines(path: &Path) -> Result<Vec<String>, String> {
    let text = std::fs::read_to_string(path).map_err(|e| {
        format!(
            "{}: {e}; a capture made before transcripts were kept has none, and \
             re-running `harness capture` for this seed makes one",
            path.display()
        )
    })?;
    Ok(text.lines().map(str::to_owned).collect())
}

/// A log line reduced to what does not vary between two runs of the same
/// server: the part after the thread name, with digits flattened.
fn shape_of(line: &str) -> String {
    // `[16:21:05] [Server thread/INFO]: Done (8.385s)!` — everything up to and
    // including the second `]: ` is per-run bookkeeping.
    let message = match line.split_once("]: ") {
        Some((_, rest)) => rest,
        None => line,
    };
    // The severity is kept, because an INFO and an ERROR carrying the same
    // words are not the same event.
    let severity = line
        .rsplit_once('/')
        .and_then(|(_, rest)| rest.split_once("]:"))
        .map_or("", |(level, _)| level);
    let mut shaped = String::with_capacity(message.len() + severity.len() + 1);
    shaped.push_str(severity);
    shaped.push(' ');
    let mut in_digits = false;
    for ch in message.chars() {
        if ch.is_ascii_digit() {
            if !in_digits {
                shaped.push('#');
                in_digits = true;
            }
        } else {
            in_digits = false;
            shaped.push(ch);
        }
    }
    shaped
}

/// What a rewrite touched. Counted rather than assumed: the module docs say why
/// a run that carries nothing through is a finding.
#[derive(Debug, Default, PartialEq, Eq)]
struct Report {
    regions: usize,
    chunks: usize,
    block_entities: usize,
    block_ticks: usize,
    fluid_ticks: usize,
}

/// Read every chunk of every region file and write it straight back.
///
/// In place, into the same region file, which the region layer supports and
/// which keeps the sector arithmetic honest: a rewritten chunk is very nearly
/// the same size as the one it replaces, and a writer that could only append
/// would not be exercising the allocator the running server uses.
fn rewrite_world(region_dir: &Path, names: &RegistryNames) -> Result<Report, String> {
    let mut report = Report::default();
    let mut files: Vec<(RegionPos, PathBuf)> = Vec::new();
    let entries = std::fs::read_dir(region_dir)
        .map_err(|e| format!("could not read {}: {e}", region_dir.display()))?;
    for entry in entries {
        let entry = entry.map_err(|e| format!("could not read {}: {e}", region_dir.display()))?;
        let path = entry.path();
        if let Some(pos) = region_pos_of(&path) {
            files.push((pos, path));
        }
    }
    // Sorted so a run's output reads the same twice and a failure names a
    // reproducible file rather than whichever the directory happened to yield.
    files.sort_by_key(|(pos, _)| (pos.x, pos.z));

    for (pos, path) in files {
        let mut file = RegionFile::open_in(region_dir, pos)
            .map_err(|e| format!("could not open {}: {e}", path.display()))?;
        let positions: Vec<ChunkPos> = file.chunk_positions().collect();
        for chunk_pos in positions {
            // Carried, not restamped. A rewrite is not a modification of the
            // world, and stamping "now" on every chunk would tell the next
            // reader something that is not true about when the world changed.
            let timestamp = file.timestamp(chunk_pos).unwrap_or(0);
            let Some(payload) = file
                .read_chunk(chunk_pos)
                .map_err(|e| format!("{} chunk {chunk_pos:?}: {e}", path.display()))?
            else {
                continue;
            };
            let named = dust_nbt::read::from_bytes(payload.as_bytes())
                .map_err(|e| format!("{} chunk {chunk_pos:?}: {e}", path.display()))?;
            let Tag::Compound(root) = &named.tag else {
                return Err(format!(
                    "{} chunk {chunk_pos:?} is not a compound",
                    path.display()
                ));
            };

            let chunk = anvil::chunk(root, WorldHeight::OVERWORLD, names)
                .map_err(|e| format!("{} chunk {chunk_pos:?}: {e}", path.display()))?;
            let carried = Carried::read_from(root);
            report.block_entities += carried
                .block_entities
                .as_ref()
                .map_or(0, dust_nbt::List::len);
            report.block_ticks += carried.block_ticks.as_ref().map_or(0, dust_nbt::List::len);
            report.fluid_ticks += carried.fluid_ticks.as_ref().map_or(0, dust_nbt::List::len);

            let written = anvil::write::chunk(&chunk, names, &carried)
                .map_err(|e| format!("{} chunk {chunk_pos:?}: {e}", path.display()))?;
            // The NBT root's name is empty in every chunk of a real world; the
            // reader above accepted whatever was there, and this is the one
            // place the writing side has to state it.
            let bytes = dust_nbt::write::to_vec("", &Tag::Compound(written))
                .map_err(|e| format!("{} chunk {chunk_pos:?}: {e}", path.display()))?;
            file.write_chunk(
                chunk_pos,
                &ChunkPayload::from_bytes(bytes),
                // Zlib, which is what every chunk of the measured world used
                // and what vanilla writes. Preserving the source chunk's scheme
                // instead would be defensible and is not more honest: this is
                // Dust writing a chunk, and Dust picks one.
                Compression::Zlib,
                timestamp,
            )
            .map_err(|e| format!("{} chunk {chunk_pos:?}: {e}", path.display()))?;
            report.chunks += 1;
        }
        report.regions += 1;
    }
    Ok(report)
}

/// `r.<x>.<z>.mca` as a region position, or `None` for anything else in the
/// directory — vanilla leaves `.mca_tmp` files behind, and a `.mcc` sibling is
/// an external chunk that belongs to a region rather than being one.
fn region_pos_of(path: &Path) -> Option<RegionPos> {
    if path.extension()?.to_str()? != "mca" {
        return None;
    }
    let stem = path.file_stem()?.to_str()?;
    let mut parts = stem.split('.');
    if parts.next()? != "r" {
        return None;
    }
    let x = parts.next()?.parse().ok()?;
    let z = parts.next()?.parse().ok()?;
    if parts.next().is_some() {
        return None;
    }
    Some(RegionPos::new(x, z))
}

fn with_suffix(dir: &Path, suffix: &str) -> PathBuf {
    let name = dir.file_name().map_or_else(
        || String::from("world"),
        |n| n.to_string_lossy().into_owned(),
    );
    dir.with_file_name(format!("{name}{suffix}"))
}

/// Copy a directory tree. Recursive and plain: a run directory is a jar-less
/// handful of files plus a world, and reaching for a crate to walk it would be
/// a dependency in a licence audit for twenty lines.
fn copy_tree(from: &Path, to: &Path) -> Result<(), String> {
    std::fs::create_dir_all(to).map_err(|e| format!("could not create {}: {e}", to.display()))?;
    let entries =
        std::fs::read_dir(from).map_err(|e| format!("could not read {}: {e}", from.display()))?;
    for entry in entries {
        let entry = entry.map_err(|e| format!("could not read {}: {e}", from.display()))?;
        let source = entry.path();
        let target = to.join(entry.file_name());
        let kind = entry
            .file_type()
            .map_err(|e| format!("could not stat {}: {e}", source.display()))?;
        if kind.is_dir() {
            copy_tree(&source, &target)?;
        } else if kind.is_file() {
            std::fs::copy(&source, &target).map_err(|e| {
                format!(
                    "could not copy {} to {}: {e}",
                    source.display(),
                    target.display()
                )
            })?;
        }
        // Symlinks are skipped rather than followed. Nothing provision writes
        // is one, and following one would copy something from outside the
        // cache into it.
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn a_region_file_name_is_recognised_by_its_two_coordinates() {
        assert_eq!(
            region_pos_of(Path::new("/w/region/r.0.0.mca")),
            Some(RegionPos::new(0, 0))
        );
        assert_eq!(
            region_pos_of(Path::new("/w/region/r.-1.2.mca")),
            Some(RegionPos::new(-1, 2))
        );
    }

    /// The three neighbours of a region file in a real world directory, each
    /// of which a looser match would pick up and then fail to open.
    #[test]
    fn nothing_else_in_a_region_directory_is_taken_for_one() {
        for path in [
            "/w/region/r.0.0.mca_tmp",
            "/w/region/c.0.0.mcc",
            "/w/region/r.0.mca",
            "/w/region/r.0.0.0.mca",
            "/w/region/session.lock",
        ] {
            assert_eq!(
                region_pos_of(Path::new(path)),
                None,
                "{path} is not a region file"
            );
        }
    }

    /// The three things that vary between two runs of the same server and must
    /// not read as new: the clock, the worker thread's number, and a progress
    /// count.
    #[test]
    fn two_runs_of_the_same_line_reduce_to_the_same_shape() {
        let a = "[16:21:03] [Worker-Main-3/INFO]: Preparing spawn area: 18%";
        let b = "[19:04:57] [Worker-Main-6/INFO]: Preparing spawn area: 51%";
        assert_eq!(shape_of(a), shape_of(b));
    }

    /// And the two that must: different words, and the same words at a
    /// different severity.
    #[test]
    fn a_different_message_and_a_different_severity_are_different_shapes() {
        let done = "[16:21:05] [Server thread/INFO]: Done (8.385s)! For help, type \"help\"";
        let chunk = "[16:21:05] [Server thread/ERROR]: Couldn't load chunk 0 0";
        assert_ne!(shape_of(done), shape_of(chunk));

        let info = "[16:21:05] [Server thread/INFO]: Couldn't load chunk 0 0";
        assert_ne!(
            shape_of(info),
            shape_of(chunk),
            "an ERROR and an INFO carrying the same words are not the same event"
        );
    }

    /// The property the whole check rests on: a message the baseline never
    /// carried is reported, and one it did is not — however many times, and
    /// whatever the numbers in it.
    #[test]
    fn only_what_the_baseline_never_said_is_new() {
        let dir = std::env::temp_dir().join("dust-rewrite-shapes");
        std::fs::create_dir_all(&dir).expect("scratch");
        let baseline = dir.join("a.log");
        let rewritten = dir.join("b.log");
        std::fs::write(
            &baseline,
            "[16:21:03] [Worker-Main-3/INFO]: Preparing spawn area: 18%
             [16:21:05] [Server thread/INFO]: Done (8.385s)!",
        )
        .expect("write");
        std::fs::write(
            &rewritten,
            "[19:04:57] [Worker-Main-6/INFO]: Preparing spawn area: 51%
             [19:04:58] [Server thread/ERROR]: Couldn't load chunk 1 2
             [19:04:58] [Server thread/ERROR]: Couldn't load chunk 3 4
             [19:05:01] [Server thread/INFO]: Done (9.001s)!",
        )
        .expect("write");

        let new = new_messages(&baseline, &rewritten).expect("both logs are there");
        assert_eq!(new.len(), 1, "two chunks, one shape: {new:?}");
        assert!(new[0].contains("Couldn't load chunk"), "{}", new[0]);

        std::fs::remove_dir_all(&dir).ok();
    }

    /// A capture made before transcripts were kept has none. That is reported
    /// rather than read as silence, because silence is the passing answer.
    #[test]
    fn a_missing_transcript_is_an_error_and_not_an_empty_one() {
        let missing = Path::new("/nonexistent/dust/server.log");
        assert!(new_messages(missing, missing).is_err());
    }

    #[test]
    fn the_rewritten_directory_is_a_sibling_of_the_source() {
        assert_eq!(
            with_suffix(Path::new("/cache/servers/1.21.1/seed-0"), "-rewritten"),
            PathBuf::from("/cache/servers/1.21.1/seed-0-rewritten")
        );
    }
}
